-- Seed soal checkpoint dari src/data/lessons.ts (server-side grading N4)
-- Generated: 2026-08-09. Idempotent: DELETE + INSERT per checkpoint.

-- 1) Pastikan kolom correct_answer_index ada (untuk grading)
ALTER TABLE public.curriculum_checkpoint_questions ADD COLUMN IF NOT EXISTS correct_answer_index integer;

-- a1-checkpoint-1 (10 soal)
DELETE FROM public.curriculum_checkpoint_questions WHERE checkpoint_id = 'a1-checkpoint-1';
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-1', 'Pilih sapaan yang tepat untuk sore hari:', '["Guten Morgen", "Guten Tag", "Guten Abend", "Gute Nacht"]'::jsonb, 2, 2, 0);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-1', 'Lengkapi kalimat: ''Ich heiße ___.''', '["du", "er", "Anna", "Sie"]'::jsonb, 2, 2, 1);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-1', 'Apa artikel yang benar untuk ''Haus''?', '["der", "die", "das", "ein"]'::jsonb, 2, 2, 2);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-1', 'Pilih artikel yang benar untuk ''Frau'':', '["der", "die", "das", "eine"]'::jsonb, 1, 1, 3);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-1', 'Bagaimana cara mengatakan ''tiga puluh dua''?', '["zweiunddreißig", "dreißigzwei", "dreizwei", "zweiunddrei"]'::jsonb, 0, 0, 4);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-1', 'Jika Anda berumur 18 tahun, apa yang Anda katakan?', '["Ich bin achtzehn Jahre alt.", "Ich bin achtzehn.", "Ich habe achtzehn Jahre.", "Ich bin acht und zehn Jahre alt."]'::jsonb, 0, 0, 5);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-1', 'Apa arti ''Tschüss''?', '["Halo", "Selamat pagi", "Sampai jumpa (informal)", "Terima kasih"]'::jsonb, 2, 2, 6);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-1', 'Lengkapi kalimat: ''Das ist ___ Apfel.''', '["die", "das", "der", "ein"]'::jsonb, 2, 2, 7);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-1', 'Apa jawaban yang tepat untuk ''Wie geht es Ihnen?'' jika kabar baik?', '["Mir geht es schlecht", "Mir geht es gut", "Nein", "Danke"]'::jsonb, 1, 1, 8);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-1', 'Berapa ''fünfzig''?', '["5", "15", "50", "100"]'::jsonb, 2, 2, 9);
-- a1-checkpoint-2 (10 soal)
DELETE FROM public.curriculum_checkpoint_questions WHERE checkpoint_id = 'a1-checkpoint-2';
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-2', 'Warna apa yang sering dikaitkan dengan matahari?', '["rot", "blau", "gelb", "grün"]'::jsonb, 2, 2, 0);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-2', 'Hari apa sebelum Freitag?', '["Mittwoch", "Donnerstag", "Samstag", "Sonntag"]'::jsonb, 1, 1, 1);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-2', 'Bulan apa yang datang setelah September?', '["August", "Oktober", "November", "Dezember"]'::jsonb, 1, 1, 2);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-2', 'Lengkapi kalimat: ''___ ist Lehrerin.''', '["Ich", "Du", "Er", "Sie"]'::jsonb, 3, 3, 3);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-2', 'Jika Anda berbicara kepada sekelompok orang secara informal, kata ganti apa yang Anda gunakan?', '["du", "Sie", "ihr", "wir"]'::jsonb, 2, 2, 4);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-2', 'Lengkapi kalimat: ''Ich ___ einen Hund.''', '["bin", "ist", "habe", "hat"]'::jsonb, 2, 2, 5);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-2', 'Pilih konjugasi ''sein'' yang benar untuk ''du'':', '["bin", "bist", "ist", "sind"]'::jsonb, 1, 1, 6);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-2', 'Apa arti ''lernen''?', '["bekerja", "belajar", "mengerti", "pergi"]'::jsonb, 1, 1, 7);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-2', 'Lengkapi kalimat: ''Wir ___ Freunde.''', '["bin", "bist", "ist", "sind"]'::jsonb, 3, 3, 8);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-2', 'Apa konjugasi ''haben'' untuk ''er''?', '["habe", "hast", "hat", "haben"]'::jsonb, 2, 2, 9);
-- a1-checkpoint-3 (10 soal)
DELETE FROM public.curriculum_checkpoint_questions WHERE checkpoint_id = 'a1-checkpoint-3';
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-3', 'Lengkapi kalimat: ''Ich ___ einen Film.''', '["esse", "trinke", "sehe", "höre"]'::jsonb, 2, 2, 0);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-3', 'Apa bentuk Akkusativ dari ''der Apfel''?', '["der Apfel", "die Apfel", "das Apfel", "den Apfel"]'::jsonb, 3, 3, 1);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-3', 'Lengkapi kalimat: ''Das Buch ist ___ dem Stuhl.''', '["in", "auf", "an", "unter"]'::jsonb, 1, 1, 2);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-3', 'Pilih preposisi yang berarti ''di depan'':', '["in", "auf", "vor", "hinter"]'::jsonb, 2, 2, 3);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-3', 'Apa bentuk Dativ dari ''die Schule''?', '["der Schule", "die Schule", "dem Schule", "den Schule"]'::jsonb, 0, 0, 4);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-3', 'Lengkapi kalimat: ''Das ist ___ Mutter.''', '["mein", "meine", "meinen", "meiner"]'::jsonb, 1, 1, 5);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-3', 'Apa bentuk maskulin dari ''die Ärztin''?', '["der Arzt", "der Ärztin", "das Arzt", "die Arzt"]'::jsonb, 0, 0, 6);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-3', 'Jika Anda memiliki anak laki-laki, apa yang Anda katakan?', '["Ich habe eine Tochter.", "Ich habe einen Sohn.", "Ich habe eine Schwester.", "Ich habe einen Bruder."]'::jsonb, 1, 1, 7);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-3', 'Apa arti ''schreiben''?', '["membaca", "menulis", "mendengar", "melihat"]'::jsonb, 1, 1, 8);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a1-checkpoint-3', 'Lengkapi kalimat: ''Die Katze ist ___ dem Tisch.'' (di bawah)', '["in", "auf", "an", "unter"]'::jsonb, 3, 3, 9);
-- a2-checkpoint-1 (10 soal)
DELETE FROM public.curriculum_checkpoint_questions WHERE checkpoint_id = 'a2-checkpoint-1';
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-1', 'Pilih artikel Akkusativ yang benar: ''Ich habe ____ Katze.''', '["der", "den", "die", "das"]'::jsonb, 2, 2, 0);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-1', 'Preposisi ''mit'' selalu diikuti oleh kasus apa?', '["Nominativ", "Akkusativ", "Dativ", "Genitiv"]'::jsonb, 2, 2, 1);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-1', 'Lengkapi kalimat dengan modal verb yang tepat: ''Er ____ nicht schwimmen.'' (tidak bisa)', '["muss", "will", "kann", "darf"]'::jsonb, 2, 2, 2);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-1', 'Apa bentuk Dativ dari ''das Kind''?', '["das Kind", "dem Kind", "den Kind", "der Kind"]'::jsonb, 1, 1, 3);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-1', 'Identifikasi kasus dari ''den Apfel'' dalam kalimat: ''Sie isst den Apfel.''', '["Nominativ", "Akkusativ", "Dativ", "Genitiv"]'::jsonb, 1, 1, 4);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-1', 'Kalimat mana yang menggunakan Dativ dengan benar?', '["Ich gebe der Mann ein Buch.", "Er hilft dem Kind.", "Wir fahren mit das Auto.", "Das gehört die Frau."]'::jsonb, 1, 1, 5);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-1', 'Konjugasi ''müssen'' untuk ''wir'' adalah:', '["muss", "musst", "müssen", "müsst"]'::jsonb, 2, 2, 6);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-1', 'Lengkapi kalimat: ''Ich danke ____ Hilfe.''', '["dir", "dich", "du", "dein"]'::jsonb, 0, 0, 7);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-1', 'Dalam kalimat ''Ich will Deutsch lernen.'', ''lernen'' adalah:', '["Kata kerja terkonjugasi", "Kata kerja modal", "Infinitif", "Partizip II"]'::jsonb, 2, 2, 8);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-1', 'Pilih artikel Nominativ yang benar: ''____ Buch ist interessant.''', '["Der", "Den", "Die", "Das"]'::jsonb, 3, 3, 9);
-- a2-checkpoint-2 (10 soal)
DELETE FROM public.curriculum_checkpoint_questions WHERE checkpoint_id = 'a2-checkpoint-2';
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-2', 'Lengkapi kalimat Perfekt: ''Ich ____ gestern einen Film ____.''', '["bin, gesehen", "habe, gesehen", "bin, sehen", "habe, sehen"]'::jsonb, 1, 1, 0);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-2', 'Pilih bentuk Präteritum yang benar untuk ''haben'' (er/sie/es):', '["hat", "hatte", "habt", "hätte"]'::jsonb, 1, 1, 1);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-2', 'Kalimat mana yang menggunakan Akkusativ dengan Wechselpräposition?', '["Das Buch liegt auf dem Tisch.", "Ich gehe in den Park.", "Die Katze sitzt unter dem Stuhl.", "Das Bild hängt an der Wand."]'::jsonb, 1, 1, 2);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-2', 'Apa Partizip II dari ''gehen''?', '["gegangen", "gegeht", "gehen", "ging"]'::jsonb, 0, 0, 3);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-2', 'Lengkapi kalimat: ''Sie ____ nicht kommen.'' (dulu tidak bisa)', '["kann", "konnte", "könnte", "können"]'::jsonb, 1, 1, 4);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-2', 'Preposisi ''in'' diikuti Dativ jika menjawab pertanyaan apa?', '["Wohin?", "Wann?", "Wo?", "Wie?"]'::jsonb, 2, 2, 5);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-2', 'Kalimat ''Wir sind nach Hause gefahren.'' menggunakan kata kerja bantu apa?', '["haben", "sein", "werden", "dürfen"]'::jsonb, 1, 1, 6);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-2', 'Apa singkatan dari ''in dem''?', '["ins", "im", "am", "ans"]'::jsonb, 1, 1, 7);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-2', 'Dalam kalimat ''Ich wollte ein Eis.'', ''wollte'' adalah bentuk waktu apa?', '["Präsens", "Perfekt", "Präteritum", "Futur I"]'::jsonb, 2, 2, 8);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-2', 'Kata kerja mana yang menggunakan ''sein'' sebagai kata kerja bantu dalam Perfekt?', '["essen", "kaufen", "schlafen", "fliegen"]'::jsonb, 3, 3, 9);
-- a2-checkpoint-3 (10 soal)
DELETE FROM public.curriculum_checkpoint_questions WHERE checkpoint_id = 'a2-checkpoint-3';
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-3', 'Pilih bentuk Komparativ yang benar dari ''gut'':', '["gut", "besser", "am besten", "beste"]'::jsonb, 1, 1, 0);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-3', 'Lengkapi kalimat dengan ''trennbare Verb'': ''Ich ____ das Fenster ____.'' (membuka)', '["mache, auf", "aufmache, das Fenster", "mache auf, das Fenster", "aufmache, es"]'::jsonb, 0, 0, 1);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-3', 'Kata tanya ''Wem?'' digunakan untuk bertanya tentang:', '["Subjek Nominativ", "Objek Akkusativ", "Objek Dativ", "Waktu"]'::jsonb, 2, 2, 2);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-3', 'Kalimat mana yang menggunakan Superlativ predikatif dengan benar?', '["Das ist der schnellste Auto.", "Sie singt am schönsten.", "Er ist besser Student.", "Ich esse am liebste Pizza."]'::jsonb, 1, 1, 3);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-3', 'Apa yang terjadi pada awalan ''trennbare Verben'' dalam kalimat subordinat?', '["Terpisah dan di akhir kalimat", "Tetap menyatu dengan kata kerja", "Diletakkan di awal kalimat", "Dihilangkan"]'::jsonb, 1, 1, 4);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-3', 'Lengkapi kalimat: ''____ ist dein Lieblingsfilm?'' (Apa)', '["Wer", "Was", "Wo", "Wie"]'::jsonb, 1, 1, 5);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-3', 'Bentuk Superlativ atributif dari ''groß'' adalah:', '["größer", "am größten", "der größte", "größte"]'::jsonb, 2, 2, 6);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-3', 'Kalimat ''Rufst du mich an?'' berarti:', '["Apakah kamu meneleponku?", "Apakah kamu memanggilku?", "Apakah kamu menelepon saya?", "Apakah kamu menelepon saya nanti?"]'::jsonb, 0, 0, 7);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-3', 'Di mana posisi kata kerja terkonjugasi dalam W-Fragen?', '["Di awal kalimat", "Di posisi kedua", "Di akhir kalimat", "Setelah subjek"]'::jsonb, 1, 1, 8);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('a2-checkpoint-3', 'Lengkapi kalimat: ''Ich stehe ____ auf.'' (pagi)', '["früh", "spät", "oft", "nie"]'::jsonb, 0, 0, 9);
-- b1-checkpoint-1 (10 soal)
DELETE FROM public.curriculum_checkpoint_questions WHERE checkpoint_id = 'b1-checkpoint-1';
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-1', 'Pilih bentuk Genitiv yang benar: ''Die Geschichte _____ (die Stadt) ist sehr alt.''', '["der Stadt", "die Stadt", "den Stadt", "des Stadt"]'::jsonb, 0, 0, 0);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-1', 'Lengkapi kalimat relatif: ''Das ist der Mann, _____ ich gestern getroffen habe.''', '["den", "der", "dem", "dessen"]'::jsonb, 0, 0, 1);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-1', 'Pilih bentuk Konjunktiv II yang benar: ''Wenn ich mehr Geld _____, würde ich ein neues Auto kaufen.''', '["hätte", "habe", "hatte", "bin"]'::jsonb, 0, 0, 2);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-1', 'Preposisi mana yang diikuti oleh Genitiv?', '["während", "mit", "nach", "aus"]'::jsonb, 0, 0, 3);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-1', 'Lengkapi kalimat relatif: ''Die Frau, _____ Kinder im Garten spielen, ist meine Nachbarin.''', '["deren", "die", "der", "denen"]'::jsonb, 0, 0, 4);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-1', 'Apa arti dari ''Ich könnte dir helfen''?', '["Saya bisa membantumu (hipotetis)", "Saya harus membantumu", "Saya akan membantumu", "Saya ingin membantumu"]'::jsonb, 0, 0, 5);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-1', 'Bagaimana bentuk Genitiv dari ''das Kind''?', '["des Kindes", "dem Kind", "das Kind", "der Kind"]'::jsonb, 0, 0, 6);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-1', 'Dalam kalimat relatif, di mana posisi kata kerja?', '["Di akhir kalimat", "Di awal kalimat", "Setelah kata ganti relatif", "Sebelum kata ganti relatif"]'::jsonb, 0, 0, 7);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-1', 'Pilih bentuk Konjunktiv II yang benar: ''Es _____ schön, wenn du mitkommen _____.''', '["wäre, könntest", "ist, kannst", "wird, wirst", "hat, hast"]'::jsonb, 0, 0, 8);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-1', 'Lengkapi kalimat: ''Trotz _____ (das schlechte Wetter) gingen wir spazieren.''', '["des schlechten Wetters", "dem schlechten Wetter", "der schlechten Wetter", "das schlechte Wetter"]'::jsonb, 0, 0, 9);
-- b1-checkpoint-2 (10 soal)
DELETE FROM public.curriculum_checkpoint_questions WHERE checkpoint_id = 'b1-checkpoint-2';
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-2', 'Ubah kalimat aktif menjadi pasif Präsens: ''Man baut ein neues Haus.''', '["Ein neues Haus wird gebaut.", "Ein neues Haus wurde gebaut.", "Ein neues Haus ist gebaut.", "Ein neues Haus baut."]'::jsonb, 0, 0, 0);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-2', 'Lengkapi kalimat dengan konjungsi yang tepat: ''Sie mag _____ Schokolade _____ Eis.''', '["weder...noch", "entweder...oder", "sowohl...als auch", "nicht nur...sondern auch"]'::jsonb, 0, 0, 1);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-2', 'Ubah kalimat langsung menjadi tidak langsung: ''Er sagte: ''Ich habe Hunger.''''', '["Er sagte, er habe Hunger.", "Er sagte, er hat Hunger.", "Er sagte, er hätte Hunger.", "Er sagte, er würde Hunger haben."]'::jsonb, 0, 0, 2);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-2', 'Bagaimana bentuk Passiv Präteritum dari ''schreiben''?', '["wurde geschrieben", "wird geschrieben", "ist geschrieben", "hat geschrieben"]'::jsonb, 0, 0, 3);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-2', 'Pilih konjungsi yang tepat: ''_____ du fleißiger bist, _____ besser werden deine Noten.''', '["Je...desto", "Entweder...oder", "Weder...noch", "Sowohl...als auch"]'::jsonb, 0, 0, 4);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-2', 'Kapan ''durch'' digunakan dalam kalimat pasif?', '["Untuk penyebab atau sarana", "Untuk pelaku orang", "Untuk objek langsung", "Untuk objek tidak langsung"]'::jsonb, 0, 0, 5);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-2', 'Ubah kalimat langsung menjadi tidak langsung: ''Sie fragte: ''Wann kommst du?''''', '["Sie fragte, wann ich käme.", "Sie fragte, wann ich komme.", "Sie fragte, wann ich kommen würde.", "Sie fragte, wann ich kam."]'::jsonb, 0, 0, 6);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-2', 'Apa arti dari ''nicht nur...sondern auch''?', '["Tidak hanya...tetapi juga", "Baik...atau", "Tidak...maupun", "Semakin...semakin"]'::jsonb, 0, 0, 7);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-2', 'Kalimat mana yang menggunakan Passiv Präsens dengan benar?', '["Das Essen wird gekocht.", "Das Essen kocht.", "Das Essen hat gekocht.", "Das Essen ist gekocht."]'::jsonb, 0, 0, 8);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-2', 'Pilih konjungsi yang tepat: ''Einerseits ist es teuer, _____ ist es sehr praktisch.''', '["andererseits", "oder", "noch", "als auch"]'::jsonb, 0, 0, 9);
-- b1-checkpoint-3 (10 soal)
DELETE FROM public.curriculum_checkpoint_questions WHERE checkpoint_id = 'b1-checkpoint-3';
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-3', 'Lengkapi kalimat dengan ''zu + Infinitiv'': ''Es ist wichtig, _____ (sprechen) Deutsch.''', '["Deutsch zu sprechen", "Deutsch sprechen", "Deutsch gesprochen", "Deutsch zu gesprochen"]'::jsonb, 0, 0, 0);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-3', 'Pilih akhiran adjektiva yang benar (deklinasi lemah): ''Ich mag den _____ (blau) Himmel.''', '["blauen", "blaue", "blaues", "blauer"]'::jsonb, 0, 0, 1);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-3', 'Lengkapi kalimat dengan Futur I: ''Wir _____ (reisen) nächsten Sommer.''', '["werden reisen", "haben gereist", "sind gereist", "reisen"]'::jsonb, 0, 0, 2);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-3', 'Apa fungsi ''ohne...zu''?', '["Menyatakan tanpa melakukan sesuatu", "Menyatakan tujuan", "Menyatakan sebab", "Menyatakan kondisi"]'::jsonb, 0, 0, 3);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-3', 'Pilih akhiran adjektiva yang benar (deklinasi campuran): ''Sie hat ein _____ (neu) Handy.''', '["neues", "neue", "neuen", "neuer"]'::jsonb, 0, 0, 4);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-3', 'Lengkapi kalimat dengan Futur II: ''Bis nächste Woche _____ er das Projekt _____ (beenden).''', '["wird...beendet haben", "wird...beenden", "hat...beendet", "ist...beendet"]'::jsonb, 0, 0, 5);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-3', 'Kalimat mana yang menggunakan ''um...zu'' dengan benar?', '["Ich lerne, um besser zu werden.", "Ich lerne, um besser werden.", "Ich lerne, besser zu werden.", "Ich lerne, um zu werden besser."]'::jsonb, 0, 0, 6);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-3', 'Pilih akhiran adjektiva yang benar (deklinasi kuat): ''_____ (frisch) Brot schmeckt gut.''', '["Frisches", "Frische", "Frischen", "Frischer"]'::jsonb, 0, 0, 7);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-3', 'Apa perbedaan utama antara Futur I dan Futur II?', '["Futur I untuk masa depan, Futur II untuk masa depan yang sudah selesai", "Futur I untuk masa lalu, Futur II untuk masa depan", "Futur I untuk fakta, Futur II untuk kemungkinan", "Tidak ada perbedaan"]'::jsonb, 0, 0, 8);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b1-checkpoint-3', 'Kalimat ''Er wird wohl schon angekommen sein'' adalah contoh dari...', '["Futur II (asumsi masa lalu)", "Futur I (prediksi masa depan)", "Präsens", "Präteritum"]'::jsonb, 0, 0, 9);
-- b2-checkpoint-1 (10 soal)
DELETE FROM public.curriculum_checkpoint_questions WHERE checkpoint_id = 'b2-checkpoint-1';
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-1', 'Pilih Partizip I yang tepat untuk melengkapi kalimat: ''Das ______ (lachen) Baby schlief friedlich.''', '["lachende", "gelachte", "lachend", "gelacht"]'::jsonb, 0, 0, 0);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-1', 'Pilih Partizip II yang tepat untuk melengkapi kalimat: ''Die ______ (schreiben) E-Mail war sehr lang.''', '["schreibende", "geschriebene", "schreibend", "geschrieben"]'::jsonb, 1, 1, 1);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-1', 'Ubah kalimat ''Der Mann, der singt, ist mein Nachbar.'' menjadi Partizipialkonstruktion.', '["Der singende Mann ist mein Nachbar.", "Der gesungene Mann ist mein Nachbar.", "Der Mann singend ist mein Nachbar.", "Der Mann gesungen ist mein Nachbar."]'::jsonb, 0, 0, 2);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-1', 'Pilih bentuk yang benar untuk ''das Buch, das auf dem Tisch liegt'' sebagai erweiterter Relativsatz.', '["das auf dem Tisch liegende Buch", "das auf dem Tisch gelegen Buch", "das Buch auf dem Tisch liegend", "das Buch auf dem Tisch gelegen"]'::jsonb, 0, 0, 3);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-1', 'Lengkapi kalimat: ''Die von der Regierung ______ (treffen) Maßnahmen sind umstritten.''', '["treffenden", "getroffenen", "treffend", "getroffen"]'::jsonb, 1, 1, 4);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-1', 'Pilih Modalpartikel yang tepat: ''Du bist ______ spät dran!'' (menyatakan kejutan atau ketidakpercayaan)', '["doch", "mal", "eben", "ja"]'::jsonb, 0, 0, 5);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-1', 'Pilih Modalpartikel yang tepat: ''Gib mir ______ den Stift!'' (melembutkan permintaan)', '["doch", "mal", "ja", "eben"]'::jsonb, 1, 1, 6);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-1', 'Pilih Modalpartikel yang tepat: ''Das ist ______ eine Frechheit!'' (menyatakan kemarahan/keterkejutan)', '["doch", "mal", "ja", "eben"]'::jsonb, 2, 2, 7);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-1', 'Pilih Modalpartikel yang tepat: ''Es ist ______ so, man muss es akzeptieren.'' (menyatakan penerimaan)', '["doch", "mal", "ja", "eben"]'::jsonb, 3, 3, 8);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-1', 'Manakah kalimat yang menggunakan ''erweiterter Relativsatz'' dengan benar?', '["Die von ihm geschriebene Brief war sehr persönlich.", "Die von ihm geschriebener Brief war sehr persönlich.", "Der von ihm geschriebene Brief war sehr persönlich.", "Der von ihm geschriebener Brief war sehr persönlich."]'::jsonb, 2, 2, 9);
-- b2-checkpoint-2 (10 soal)
DELETE FROM public.curriculum_checkpoint_questions WHERE checkpoint_id = 'b2-checkpoint-2';
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-2', 'Manakah kalimat yang menunjukkan gaya penulisan ilmiah yang objektif?', '["Ich finde die Studie sehr interessant.", "Es wird angenommen, dass die Studie wichtige Erkenntnisse liefert.", "Meiner Meinung nach ist die Forschung bahnbrechend.", "Wir sind überzeugt, dass die Ergebnisse stimmen."]'::jsonb, 1, 1, 0);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-2', 'Ubah kalimat ''Man hat die Ergebnisse präsentiert'' menjadi bentuk nominalisasi dan pasif.', '["Die Präsentation der Ergebnisse wurde durchgeführt.", "Die Ergebnisse wurden präsentiert.", "Man präsentierte die Ergebnisse.", "Die Ergebnisse präsentierten sich."]'::jsonb, 0, 0, 1);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-2', 'Apa fungsi utama Konjunktiv I dalam ''indirekte Rede''?', '["Menyatakan keraguan", "Menyatakan perintah", "Melaporkan pernyataan pihak ketiga tanpa menjamin kebenarannya", "Menyatakan keinginan"]'::jsonb, 2, 2, 2);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-2', 'Ubah kalimat langsung menjadi tidak langsung dengan Konjunktiv I: ''Sie sagt: ''Ich gehe jetzt nach Hause.''''', '["Sie sagt, sie ginge jetzt nach Hause.", "Sie sagt, sie geht jetzt nach Hause.", "Sie sagt, sie gehe jetzt nach Hause.", "Sie sagt, sie würde jetzt nach Hause gehen."]'::jsonb, 2, 2, 3);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-2', 'Jika bentuk Konjunktiv I dari ''wir kommen'' adalah ''wir kommen'', apa yang digunakan sebagai pengganti dalam ''indirekte Rede''?', '["wir kämen", "wir kommen", "wir würden kommen", "A atau C"]'::jsonb, 3, 3, 4);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-2', 'Pilih konjungsi yang tepat: ''______ er krank war, blieb er zu Hause.'' (sebab)', '["Obwohl", "Damit", "Weil", "Nachdem"]'::jsonb, 2, 2, 5);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-2', 'Pilih konjungsi yang tepat: ''Ich spare Geld, ______ ich mir ein neues Auto kaufen kann.'' (tujuan)', '["sodass", "damit", "indem", "während"]'::jsonb, 1, 1, 6);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-2', 'Manakah kalimat yang menggunakan Konjunktionaladverb dengan benar?', '["Es war kalt; trotzdem wir gingen spazieren.", "Es war kalt; wir gingen trotzdem spazieren.", "Es war kalt; trotzdem gingen wir spazieren.", "Es war kalt; wir trotzdem gingen spazieren."]'::jsonb, 2, 2, 7);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-2', 'Dalam kalimat ''Die Durchführung des Projekts war erfolgreich.'', ''Durchführung'' adalah contoh dari...', '["Kata kerja", "Adjektiva", "Nominalisasi", "Partizip"]'::jsonb, 2, 2, 8);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-2', 'Apa yang dimaksud dengan ''Komplexe Satzstrukturen''?', '["Kalimat yang sangat panjang", "Kalimat dengan banyak tanda baca", "Penggabungan beberapa klausa untuk mengekspresikan ide rumit", "Kalimat yang sulit dipahami"]'::jsonb, 2, 2, 9);
-- b2-checkpoint-3 (10 soal)
DELETE FROM public.curriculum_checkpoint_questions WHERE checkpoint_id = 'b2-checkpoint-3';
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-3', 'Apa arti dari idiom ''die Nase voll haben''?', '["Sangat bahagia", "Muak atau bosan", "Sedang pilek", "Mencium bau yang tidak enak"]'::jsonb, 1, 1, 0);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-3', 'Lengkapi idiom: ''Ich drücke dir die ______ für deine Prüfung!''', '["Hände", "Augen", "Daumen", "Füße"]'::jsonb, 2, 2, 1);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-3', 'Jika seseorang ''ins kalte Wasser springen'' artinya dia...', '["Berani berenang di air dingin", "Memulai sesuatu tanpa persiapan", "Melompat ke kolam renang", "Mandi air dingin"]'::jsonb, 1, 1, 2);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-3', 'Istilah ''der Patient'' termasuk dalam Fachvokabular bidang...', '["Jura", "Wirtschaft", "Medizin", "Technik"]'::jsonb, 2, 2, 3);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-3', 'Apa arti dari ''das Gesetz''?', '["Kontrak", "Pengadilan", "Undang-undang", "Hukuman"]'::jsonb, 2, 2, 4);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-3', 'Istilah ''der Umsatz'' termasuk dalam Fachvokabular bidang...', '["Medizin", "Jura", "Wirtschaft", "Politik"]'::jsonb, 2, 2, 5);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-3', 'Apa yang dimaksud dengan ''Hauptaussage'' dalam Textanalyse?', '["Kalimat pertama teks", "Pernyataan utama atau pesan sentral penulis", "Judul teks", "Ringkasan teks"]'::jsonb, 1, 1, 6);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-3', 'Manakah frasa yang tepat untuk memperkenalkan kontra-argumen?', '["Ich bin der Ansicht, dass...", "Ein wichtiges Argument dafür ist...", "Man könnte einwenden, dass...", "Zusammenfassend lässt sich sagen..."]'::jsonb, 2, 2, 7);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-3', 'Apa tujuan dari ''Argumentation''?', '["Menceritakan kisah", "Menyampaikan informasi secara netral", "Menyajikan pandangan secara logis dan meyakinkan", "Menghibur pembaca"]'::jsonb, 2, 2, 8);
INSERT INTO public.curriculum_checkpoint_questions (checkpoint_id, question, options, correct_answer, correct_answer_index, sort_order) VALUES ('b2-checkpoint-3', 'Jika Anda ingin ''membantah'' sebuah argumen, kata kerja apa yang paling tepat?', '["begründen", "belegen", "widerlegen", "überzeugen"]'::jsonb, 2, 2, 9);

-- TOTAL: 120 soal